### ISSUE TITLE
Consider using ENTRYPOINT instead of CMD

### ISSUE THREAD

**Issue by hardys** [suse-edge/edge-image-builder#197]
Currently eib container usage is like:

```
podman run -v $IMAGE_DIR:/eib eib:dev /bin/eib build ...
```

This requires knowledge of exactly where the eib binary is installed in the image, and in the case of the RPM based [OBS image](https://build.opensuse.org/package/show/isv:SUSE:Edge:EdgeImageBuilder/edge-image-builder-100rc0-image) it ends up in `/usr/bin/eib` instead.

We could change that in the OBS build so the paths align, but I'm wondering is instead we should be using ENTRYPOINT in both Dockerfiles instead, then the usage can be like this, which may be preferable unless we expect to support multiple entrypoints to the container?

```
podman run -v $IMAGE_DIR:/eib <EIB IMAGE> build ...
```

**Comment by jdob** [comment]
Potentially related to #72, though I think even with the launcher this is still a good idea to consider.
