### ISSUE TITLE
Add sane defaults for some command flags

### ISSUE THREAD

**Issue by e-minguez** [suse-edge/edge-image-builder#198]
Currently:

```
podman run --rm -it \
-v $IMAGE_DIR:/eib eib:dev /bin/eib build \
--config-file $CONFIG_FILE.yaml \
--config-dir /eib \
--build-dir /eib/_build
```

It would be nice to be able to skip at least the 'dir' parameters with sane defaults (config-dir = /eib, build-dir = /eib/_build) so if using the _default_ /eib volume mapping the command looks like:

```
podman run --rm -it \
-v $IMAGE_DIR:/eib eib:dev /bin/eib build \
--config-file $CONFIG_FILE.yaml
```

**Comment by jdob** [comment]
Issue #72 will address this.
