### ISSUE TITLE
Add an examples folder

### ISSUE THREAD

**Issue by e-minguez** [suse-edge/edge-image-builder#207]
It seems it is a good practice (?) https://github.com/golang-standards/project-layout/tree/master/examples

**Comment by jdob** [comment]
It's been on our radar, just haven't had time to yet. I'm hoping to take some of what comes out of QA and use those to populate it.

**Comment by jdob** [comment]
It's been added and is in progress of being fleshed out: https://github.com/suse-edge/edge-image-builder/tree/main/examples
