### ISSUE TITLE
K3s combustion script requires `registries.yaml` but file is not generated

### ISSUE THREAD

**Issue by koendelaat** [suse-edge/edge-image-builder#209]
# Situation:

- Kubernetes (k3s) configured in `image-config.yaml`
- Manifests files stored under: `/kubernetes/manifests` (`kind: RoleBinding`)
- No `embeddedArtifactRegistry` configured
- No `kubernetes.manifests.URLs` configured

Results in `20_k8s_install.sh`:
```shell
#!/bin/bash
set -euo pipefail

mount /var

mkdir -p /var/lib/rancher/k3s/agent/images/
cp kubernetes/images/* /var/lib/rancher/k3s/agent/images/
mkdir -p /var/lib/rancher/k3s/server/manifests/
cp kubernetes/manifests/* /var/lib/rancher/k3s/server/manifests/

umount /var

mkdir -p /etc/rancher/k3s/
cp server.yaml /etc/rancher/k3s/config.yaml
cp registries.yaml /etc/rancher/k3s/registries.yaml

export INSTALL_K3S_SKIP_DOWNLOAD=true
export INSTALL_K3S_SKIP_START=true
export INSTALL_K3S_BIN_DIR=/opt/bin

mkdir -p $INSTALL_K3S_BIN_DIR
chmod +x kubernetes/install/k3s
cp kubernetes/install/k3s $INSTALL_K3S_BIN_DIR/k3s

./k3s_installer.sh
```
# Result
Installation failed with message: `cp: cannot stat 'registries.yaml': No such file or directory`

# Investigation
pkg/combustion/registry.go
```go
func configureRegistry(ctx *image.Context) ([]string, error) {
	if !IsEmbeddedArtifactRegistryConfigured(ctx) {
		log.AuditComponentSkipped(registryComponentName)
		return nil, nil
	}
...
}
...
func IsEmbeddedArtifactRegistryConfigured(ctx *image.Context) bool {
	return len(ctx.ImageDefinition.EmbeddedArtifactRegistry.ContainerImages) != 0 ||
		len(ctx.ImageDefinition.Kubernetes.Manifests.URLs) != 0 ||
		isComponentConfigured(ctx, filepath.Join(k8sDir, helmDir))
}
```
`registries.yaml` is not written in case of local manifests files

pkg/combustion/templates/k3s-single-node-installer.sh.tpl
```yaml
...
{{- if .manifestsPath }}
cp {{ .registryMirrors }} /etc/rancher/k3s/registries.yaml
{{- end }}
...
```
When local manifests are used, `registries.yaml` is expected

**Comment by dbw7** [comment]
Thank you for catching this, just added handling for this in #210

**Comment by dbw7** [comment]
@koendelaat After further consideration of this scenario, it doesn't even make sense to start the embedded artifact registry when the provided manifests contain no images, so #211 handles this even better.

**Comment by koendelaat** [comment]
@dbw7 After #211 was merged, this issue appears again.

https://github.com/suse-edge/edge-image-builder/blob/main/pkg/combustion/templates/k3s-single-node-installer.sh.tpl#L28
```tpl
{{- if .manifestsPath }}
cp {{ .registryMirrors }} /etc/rancher/k3s/registries.yaml
{{- end }}
```
This should be conditional on: 
```go
func configureEmbeddedArtifactRegistry(ctx *image.Context) (bool, error)
```

**Comment by dbw7** [comment]
My mistake on not catching this, though now I realize that the issue is a bit trickier. 
```go
manifestsPath, err := configureManifests(ctx)
if err != nil {
	return "", fmt.Errorf("configuring kubernetes manifests: %w", err)
}

templateValues := map[string]any{
	"apiVIP":          ctx.ImageDefinition.Kubernetes.Network.APIVIP,
	"apiHost":         ctx.ImageDefinition.Kubernetes.Network.APIHost,
	"installPath":     installPath,
	"imagesPath":      imagesPath,
	"manifestsPath":   manifestsPath,
	"registryMirrors": registryMirrorsFileName,
}
```
The previous false assumption of creating a registry whenever there are manifests allowed us to use `manifestsPath` as a check, but now since we don’t even spin up the registry if there are no images in the manifests, we need to figure out a way around this using the new changes in the registry combustion component. Looking into this now.

**Comment by koendelaat** [comment]
> My mistake on not catching this, though now I realize that the issue is a bit trickier.

That's why I created an issue and not a PR 😃

**Comment by dbw7** [comment]
@koendelaat I believe this issue has been resolved but please confirm.
