### ISSUE TITLE
zypper clean after zypper install

### ISSUE THREAD

**Issue by e-minguez** [suse-edge/edge-image-builder#213]
zypper clean -a after zypper install will release ~100 Mb:

```
f18aaec58f60:~ # du -hs /var/cache/zypp/
178M	/var/cache/zypp/
f18aaec58f60:~ # zypper clean -a
All repositories have been cleaned up.
f18aaec58f60:~ # du -hs /var/cache/zypp/
0	/var/cache/zypp/
```

**Comment by jdob** [comment]
Can you give us some more context of what you're talking about here? Is this in the EIB image build itself or the RPM installation?

**Comment by e-minguez** [comment]
https://github.com/suse-edge/edge-image-builder/blob/main/Dockerfile#L31-L37

basically it is a good practice to clean up that metadata as:

zypper in foobar && zypper clean -a

https://github.com/rancher/rancher/blob/27a381bdcb70f33f22408940bc617f078f6f3835/package/Dockerfile#L3-L4
