### ISSUE TITLE
Add users to groups

### ISSUE THREAD

**Issue by e-minguez** [suse-edge/edge-image-builder#215]
It would be nice to be able to add users to groups using the configuration file. For example when adding an 'administrator' user to the wheel group so he is allowed to execute sudo commands.

It seems it is being handled https://github.com/suse-edge/edge-image-builder/blob/18e78e6c589a20b079e856651dda359f0ced576d/pkg/combustion/templates/13-add-users.sh.tpl#L12 and just in case, there is a -G flag for useradd where you can specify a list of supplementary groups for the user to belong to.

**Comment by jdob** [comment]
This was added prior to RC1; I must have forgotten to close this out.
