### ISSUE TITLE
Unable to build EIB Image on macOS - 'hauler' not found in package names'

### ISSUE THREAD

**Issue by mpas** [suse-edge/edge-image-builder#249]
I am unable to build the EIB Image on macOS and get the following error message.

```
Building repository 'Update repository with updates from SUSE Linux Enterprise 15' cache [....done]
Retrieving repository 'Update Repository (Non-Oss)' metadata [........done]
Building repository 'Update Repository (Non-Oss)' cache [...done]
Loading repository data...
Reading installed packages...
No provider of 'hauler' found.
'hauler' not found in package names. Trying capabilities.
Error: building at STEP "RUN zypper install -y     xorriso squashfs      libguestfs kernel-default e2fsprogs parted gptfdisk btrfsprogs gues
tfs-tools lvm2     podman     createrepo_c     helm hauler     nm-configurator &&     zypper clean -a": while running runtime: exit status 1
04
```

> Running on:
> - OS: macOS 13.6 22G120 arm64
> - Podman: 4.9.3

Previous versions of the EIB image worked perfectly!

I followed the instructions in the README but not clear why I should need all the different libraries installed as they are pulled-in via the Dockerfile.

**Comment by atanasdinov** [comment]
Hey, @mpas. Please delete the Podman image caches and rebuild.

For reference: https://github.com/suse-edge/edge-image-builder/pull/248

**Comment by mpas** [comment]
@atanasdinov Life saver! Works!! Thanks!!!
