### ISSUE TITLE
Overlapping/conflicting source repositories for NVIDIA GPU install

### ISSUE THREAD

**Issue by joostwestra** [suse-edge/edge-image-builder#250]
Thanks to the great work from @mpas we have better understanding on the dependencies required and used to get our GPU application running.

# Current situation

We currently can get it to work with by being vigilant on ordering and versioning different packages but we think the current situation is not as intended or desired.

We require the following packages for our application:

```shell
- nvidia-open-driver-G06-signed-kmp-default # the nvidia videcard driver
- nvidia-gl-G06 # opengl support
- nvidia-compute-utils-G06 # cuda utils / libraries
- nvidia-container-toolkit # container toolkit
```

 Currently we require three different repository to get all these packages:

-   SLE MICRO Repo (_SLEM_): SUSE Linux Enterprise Micro 5.5

    -   The main repository that contains packages suitable for SLE MICRO including the NVIDIA Driver for SLE MICRO.

-   NVIDIA SUSE Repo (_NVIDIA-SUSE_): https://download.nvidia.com/suse/sle15sp5/

    -   Default repository for SUSE related packages

-   NVIDIA CUDA Repo (_NIVIDIA-CUDA_): https://developer.download.nvidia.com/compute/cuda/repos/sles15/x86_64/

    -   Repository containing Cuda/Container Toolkit
    
 # And some of these packages are present in multiple of these repositories:
 
 ```mermaid
flowchart TB
    slem[SLE MICRO Repo] --> opendriver[nvidia-open-driver-G06-signed-kmp-default]
    nvidia-suse[NVIDIA SUSE Repo] --> opengl[nvidia-gl-G06]
    nvidia-suse --> compute[nvidia-compute-utils-G06]
    nvidia-cuda[NVIDIA Cuda Repo] --> container-toolkit[nvidia-container-toolkit]
    nvidia-cuda --> new
    new[!] --> opengl2[nvidia-gl-G06 !!!!]
    new[!] --> compute2[nvidia-compute-utils-G06 !!!!]
```

# All these repositories also have different update cycles:

1. The SLE MICRO repo contains multiple versions of `nvidia-open-driver-G06-signed-kmp-default`

2. The NVIDIA-SUSE and NVIDIA-CUDA repo both contain one version of `nvidia-compute-utils-G06` and `nvidia-gl-G06` but the versions can be different, no older versions are persisted :exclamation:. A newer version first gets released into the NVIDIA-CUDA and later on propagated to NVIDIA-SUSE.

3. The NVIDIA-CUDA repo contains multiple versions of the `nvidia-container-toolkit`

4. The NVIDIA-CUDA repo is updated more frequent, so the version of `nvidia-compute-utils-G06` and `nvidia-gl-G06` can be higher in the CUDA repo than in the NVIDIA repo.

# Our ask:

To us this setup of using three repositories with overlap and different update cycles appears to be overly complex and error prone.  Can you technically improve this situation or give us guidance on why it needs to be this complex?

**Comment by rdoxenham** [comment]
@joostwestra @mpas - can you please take a look at https://github.com/suse-edge/suse-edge.github.io/pull/103 please? I think that the CUDA repo that we were pulling in before is causing us plenty of trouble as it seems to be a superset of RPM's, where we really only need the `nvidia-container-toolkit` which we can pull from a specific repo. I've tried to extensively update the documentation that should make all of this clear, and have added a section for EIB. Your feedback is appreciated. Thank you!

**Comment by joostwestra** [comment]
Checken and tested. Thanks for the quick update!
 I do get an lspci not found pop up during install, but it appears this is not required
