### ISSUE TITLE
kernel cmdline args are added, not replaced

### ISSUE THREAD

**Issue by hardys** [suse-edge/edge-image-builder#264]
Building an image with a config like:

```
operatingSystem:
  kernelArgs:
  - ignition.platform.id=openstack
  - net.ifnames=1
```

Results in a kernel cmdline like:

```
 cat /proc/cmdline 
BOOT_IMAGE=/boot/vmlinuz-5.14.21-150500.55.19-default root=UUID=ba0a3c19-afc9-4ae1-9ff5-524c78b93d3a rd.timeout=60 console=ttyS0,115200 console=tty0 security=selinux selinux=1 quiet net.ifnames=0 ignition.firstboot dasd_mod.dasd=autodetect ignition.platform.id=metal ignition.platform.id=openstack net.ifnames=1
```

The args are only appended, the existing entries should also be removed?

**Comment by rdoxenham** [comment]
Whilst we should probably remove additional entries, this is actually okay... you can duplicate kernel cmdline arguments and the final one is the one that's taken.

**Comment by jdob** [comment]
Yeah, like Rhys said, this was an intentional shortcut for now. It's not ideal, but the alternative of trying to actually parse and work with those was too much for 1.0.

**Comment by jdob** [comment]
In the interest of keeping this issue backlog readable, we're going to close this one. If this arises as a bug that's stopping it from working, we can reopen as a bug. For now, in reality we don't see when we'd ever have the cycles to address it until it becomes an actual problem.
