### ISSUE TITLE
Custom files should keep their permissions

### ISSUE THREAD

**Issue by e-minguez** [suse-edge/edge-image-builder#272]
For some use cases, the users would like to add executable files or scripts via combustion. In order to do so, the custom/files folder is being used.
However, even if the files/scripts are there with an executable flag, EIB seems to remove it here https://github.com/suse-edge/edge-image-builder/blob/main/pkg/combustion/custom.go#L44C61-L44C86

The workaround is to add a script that does the chmod a+x or whatever is needed but it would be nice if it keeps the permissions as the original ones.

**Comment by atanasdinov** [comment]
Files are copied as [non-executable](https://github.com/suse-edge/edge-image-builder/blob/main/pkg/combustion/custom.go#L44) whereas scripts are copied as [executables](https://github.com/suse-edge/edge-image-builder/blob/main/pkg/combustion/custom.go#L50). Doesn't this account for the requirements?

**Comment by e-minguez** [comment]
Unfortunately no. Why does it need to change the original permissions? :) I want to be able to add an executable to my final system and in order to do it the only way right now is to drop it into the custom/files folder AND have a script on the custom/scripts that does a chmod...

**Comment by atanasdinov** [comment]
Understood! We'll look into it.
