### ISSUE TITLE
Permissions error attemping to modify a raw image

### ISSUE THREAD

**Issue by jdob** [suse-edge/edge-image-builder#29]
```
$ podman run --rm -it -v ~/Code/eib/:/eib eib:dev /bin/eib -config-file raw-image.yaml -config-dir /eib -build-dir /eib/_build $@
2023-11-02T17:01:48.740Z	fatal	eib/main.go:122	An error occurred building the image	{"error": "running the image modification script: fork/exec /eib/_build/modify-raw-image.sh: permission denied"}
main.main
	/src/cmd/eib/main.go:122
runtime.main
	/usr/lib64/go/1.21/src/runtime/proc.go:267
```

Looking into the generated build directory, the `modify-raw-image.sh` script doesn't have execute permissions. I'm not sure if that's the cause (or what would have caused that to change over the past few days), but it's worth looking into.

**Comment by jdob** [comment]
Ahh, I wonder if it was the change to using templates instead of Go substitution. Not sure why that would do it, but the timing checks out.

**Comment by atanasdinov** [comment]
You're most certainly correct. [os.Create()](https://pkg.go.dev/os@go1.21.3#Create) will use 0666 as a permission mode whereas it was previously set to 0777 (via `os.ModePerm`).
