### ISSUE TITLE
Side-loading RPMs fails without a gpg-key directory

### ISSUE THREAD

**Issue by jdob** [suse-edge/edge-image-builder#295]
I have an `rpms` directory with a single RPM:

```
$ ll rpms
-rw-r--r-- 1 jdobies jdobies 7184616 Mar 12 09:49 elemental-system-agent-0.3.3-150500.5.3.x86_64.rpm
```

When building the image, it fails with the following error:

```
2024-03-12T13:49:31.819Z	INFO	combustion/rpm.go:36	Configuring RPM component...
2024-03-12T13:49:31.819Z	FATAL	build/build.go:92	An error occurred building the image: configuring combustion: configuring component "RPM": GPG validation is enabled, but 'gpg-keys' directory is missing for side-loaded RPMs
github.com/suse-edge/edge-image-builder/pkg/cli/build.Run
	/src/pkg/cli/build/build.go:92
github.com/urfave/cli/v2.(*Command).Run
	/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/command.go:279
github.com/urfave/cli/v2.(*Command).Run
	/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/command.go:272
github.com/urfave/cli/v2.(*App).RunContext
	/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/app.go:337
github.com/urfave/cli/v2.(*App).Run
	/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/app.go:311
main.main
	/src/cmd/eib/main.go:18
runtime.main
	/usr/lib64/go/1.22/src/runtime/proc.go:271
```

This issue is to either:
* Correct this behavior if it's not desired
* Update the EIB docs to indicate the `gpg-keys` directory is needed (it currently makes no mention of this directory)

**Comment by rdoxenham** [comment]
@atanasdinov interesting one... if we supply the Elemental config, we automatically grab the Elemental RPM's, but if we side-load them, e.g. because the customer may want to use a dev/experimental RPM, would we end up still grabbing the one we ship with? I think we would, wouldn't we? That would be multiple RPM's being installed? Thoughts?

**Comment by atanasdinov** [comment]
Well, we'd still download them. I don't think it makes sense for the user to ever provide Elemental RPMs though... Isn't this the point of making Elemental a first-class citizen?
