### ISSUE TITLE
Combustion fails when combustion directory content is larger than half of the RAM of the system

### ISSUE THREAD

**Issue by dbw7** [suse-edge/edge-image-builder#319]
[Combustion](https://github.com/openSUSE/combustion#combustion) works by copying all of the contents of the combustion directory into `/dev/shm/combustion/config`. During combustion, `/dev/shm` can use up to half of the system's RAM. In the situation where the size of the contents of the combustion directory exceeds half of the system's RAM, combustion will fail with this error:
```
[   18.546874] localhost combustion[725]: cp: error writing '/dev/shm/combustion//config/MYFILE': No space left on device
```

The current recommended solution is:

> Place big files outside of that folder (/combustion) and inside the combustion script do mount /dev/disk/by-label/combustion /mnt and access the drive directly

**Comment by ipetrov117** [comment]
This applies to the `rpm-repo` directory that is currently at `/combustion`. It has the potential to seriously grow in size, depending on how many RPMs does the user want to install. I am sure you have this in mind, but I wanted to put this here so we do not miss it.

**Comment by e-minguez** [comment]
Just FYI I've been trying to deploy a cluster with a few helm charts for edge components (metal3, longhorn, cert-manager & rancher, the only one left was the neuvector one) and this happened to me.
