### ISSUE TITLE
Add EIB version to the the CLI and to built images

### ISSUE THREAD

**Issue by e-minguez** [suse-edge/edge-image-builder#354]
https://github.com/suse-edge/edge-image-builder/blob/d940dfe1dc01a70e6a525b1a07f593fa5a1bbc6b/pkg/combustion/templates/48-message.sh#L3

It would be nice to have the EIB version being used there.

**Comment by jdob** [comment]
Additionally, we need to add a command that outputs the current version of EIB for customer support case purposes.
