### ISSUE TITLE
Question: any documentation available why I need to mount certain volumes to persist data?

### ISSUE THREAD

**Issue by mpas** [suse-edge/edge-image-builder#382]
Hi there, I am wondering if there is any documentation available that makes understanding the volumes mounts?

I have tried to create a custom script that saves a file to `/var/lib/rancher/k3s/server`

```
# this does not work, the file is gone later on
mkdir -p /var/lib/rancher/k3s/server
cp k3s-psa.yaml /var/lib/rancher/k3s/server/k3s-psa.yaml
```

```
# this does work, and the file is persisted when mounting /var
mount /var
mkdir -p /var/lib/rancher/k3s/server
cp k3s-psa.yaml /var/lib/rancher/k3s/server/k3s-psa.yaml
umount /var
```

I want to understand why the `/var` mount is required to persist the file.

**Comment by atanasdinov** [comment]
Hey, @mpas. This is not quite clear in the [official SLE Micro documentation](https://documentation.suse.com/sle-micro/5.5/single-html/SLE-Micro-deployment/#sec-default-partitioning) and we've requested for it to be updated.

In the meantime, note that you have to mount `/var`, `/usr/local` and `/home` if you intend to use those volumes. The ones mounted by default include `/etc` and `/opt`.

**Comment by atanasdinov** [comment]
@mpas the documentation is now updated and it explains the process to fetch the list of mounted volumes.

Closing as completed. Feel free to reopen if you have further questions.
