### ISSUE TITLE
Make component Helm charts configurable at build time

### ISSUE THREAD

**Issue by atanasdinov** [suse-edge/edge-image-builder#419]
Names and versions of Helm charts can change and those are currently being [hardcoded](https://github.com/suse-edge/edge-image-builder/blob/main/pkg/combustion/helm.go). We need to provide the option to configure them either by extracting global variables which can be modified at build time or via a configuration file of some sort.

**Comment by e-minguez** [comment]
Related https://github.com/suse-edge/edge-image-builder/issues/370 ?

**Comment by atanasdinov** [comment]
Not really. One aims to address the naming and versioning of the Helm charts so downstream builds can modify those while the other (#370) is looking to allow upstream builds to use downstream charts.
