### ISSUE TITLE
SUMA Documentation suggests 

### ISSUE THREAD

**Issue by rdoxenham** [suse-edge/edge-image-builder#420]
In SUMA section in building-images.md we talk about grabbing the RHN-ORG-TRUSTED-SSL-CERT file, but we only pick this up in certificates.go if the files are .pem or .crt (https://github.com/suse-edge/edge-image-builder/blob/main/pkg/combustion/certificates.go#L63-L69)

Which results in certificates getting triggered, but no files copied over, hence system boot failure:

![image](https://github.com/suse-edge/edge-image-builder/assets/1042177/9ed70463-07b2-4cbd-83fd-f0f7eb63ff89)

This is picked up correctly if the file is renamed:

```
rdo@woden:~/work/eib-testing/_build/build-Apr22_15-51-47/combustion% ls
05-configure-network.sh  10-rpm-install.sh  12-keymap-setup.sh  14-systemd.sh            48-message.sh  certificates  nmc
07-certificates.sh       11-time-setup.sh   13b-add-users.sh    30-suma-registration.sh  60-fixboot.sh  network       script
rdo@woden:~/work/eib-testing/_build/build-Apr22_15-51-47/combustion% ls certificates
rhn.pem
```

**Comment by jdob** [comment]
I'm not 100% sure I follow. Is the request to remove the requirement for the files to end in .crt or .pem and instead include everything in that directory? 

I might be missing something, but you mention us talking about the certificates in the SUMA section, but I don't actually see any references to certificates in there. Can you point me to the line you're talking about?

**Comment by jdob** [comment]
Closing out as inactive; feel free to reopen if this is still an issue.
