### ISSUE TITLE
FR: Non-static directory structure for EIB or a script to create the structure and explain it

### ISSUE THREAD

**Issue by peteingithub** [suse-edge/edge-image-builder#453]
Currently EIB looks content from hard coded directories. 
Would it make any benefit to add a config file in the EIB directory root to configure where certain info (e.g.  base-images)  can be found? 
Or maybe add a script to create the required structure and give output what's where.

**Comment by jdob** [comment]
Thanks for the suggestion :) The rigid directory structure was an intentional decision that we made in hopes of minimizing the difficulty in onboarding. There are no current plans to allow that to be flexible due to the complications that may arise. However, if in the future we do revisit this decision I'll reopen this issue.

**Comment by peteingithub** [comment]
Understandable. Would make things more complex anyway.
 
How about improving the product usability further having a script to create the structure and some necessary files should there be default settings such as for 'cilium'?

**Comment by jdob** [comment]
I've thought about it, an `eib init` sort of thing. But outside of creating the `base-images` directory and the first few lines of the definition (which would still need to be edited), I didn't imagine there was much else it would do. But I'm open to it, do you have any more ideas of what else could be initialized in this way?

**Comment by peteingithub** [comment]
I'm thinking about 'init mgmt-cluster' and 'init downstream-cluster'.

I'd have the directories and sample files created based on: 
'https://suse-edge.github.io/atip-management-cluster.html#mgmt-cluster-directory-structure'

I'd also have full commented-out sample configuration from:
`https://suse-edge.github.io/atip-management-cluster.html#mgmt-cluster-directory-structure`
(Added with longhorn.yaml for setting replicas to 1.)

Similar init for a sample downstream cluster.

You'd need to modify a bunch of config files, right, but those would be then be easily done while un-commenting stuff. The documentation in this part is really good in my opinion, if followed properl. (I screwed up here and there, so having everything ready from the get go, would in any case help.)

**Comment by peteingithub** [comment]
Not sure if it would possible, but how about a source file for the variables that need to be unique in ones environment, which then would be used to populate the manifest files for image creation. (Thinking out loud here.)

**Comment by jdob** [comment]
> Not sure if it would possible, but how about a source file for the variables that need to be unique in ones environment, which then would be used to populate the manifest files for image creation. (Thinking out loud here.)

This is definitely on our radar, and something that's been personally biting me a bit recently. I'll look around for the Issue link (I think there is one, but I worry it's conflated with our RFE around handling sensitive data) and post it later.

To your other comments, I see what you're getting at. We definitely could use a bit of love in our on boarding for brand new projects. It's something we kinda tried to answer with the `/examples` directory but it's not there yet. Lemme look into what this may look like.

Thanks for the feedback, this sort of thing is really useful :)
