### ISSUE TITLE
EIB Versioning

### ISSUE THREAD

**Issue by dbw7** [suse-edge/edge-image-builder#457]
EIB users should be able to see what version of EIB they are running by using an `eib version` command. Additionally, CRB images should have the version of EIB that was used to build that image next to the "Configured with the Edge Image Builder" message.

**Comment by e-minguez** [comment]
https://github.com/suse-edge/edge-image-builder/issues/354

**Comment by dbw7** [comment]
My mistake, I didn't dig deep enough into the issues.
