### ISSUE TITLE
docs: Add information about to use "SelfInstall" MicroOS and not the "DVD" version.

### ISSUE THREAD

**Issue by jomeier** [suse-edge/edge-image-builder#482]
Hi,

docs should mention, that users must use (Open)Suse MicroOS ["SelfInstall"](https://get.opensuse.org/microos/) and not "DVD" versions!
"DVD" versions of MicroOS won't work with EIB. Instead an error message about a missing "*.squashfs" file will be thrown out.

Thanks and greetings,

Josef

**Comment by jdob** [comment]
@jomeier Thanks for the suggestion, it's one of those things that was tribal knowledge to us and we forgot to document. I added a section to the building images guide talking about the supported image types and some guidance on the ISO differences. Please let me know if you don't think this is sufficient.
