### ISSUE TITLE
Output built image location after building

### ISSUE THREAD

**Issue by agracey** [suse-edge/edge-image-builder#489]
It would be very helpful to have the image location printed out at the end of the build process. That way I can copy it easily instead of needing to look in the config file or at timestamps for which one I built last.

**Comment by jdob** [comment]
I thought this would be an easy fix, but the full image location isn't actually known to EIB. EIB only knows about the directory mounted into the EIB container; it has no idea what directory on the host machine was used for the build. I'll add a message that shows the name of the built image, but there's no way to have it output the full location.
