### ISSUE TITLE
Question: Upgrade strategy for SLE Micro / RKE2 and Longhorn data? Seperate data partition? EIB config?

### ISSUE THREAD

**Issue by jomeier** [suse-edge/edge-image-builder#497]
Hi,
I experiment with EIB since a few weeks and ask myself, what the best strategy is to update SLE Micro and RKE2 but keep configuration  and data,

Currently I only have one partition where everything is installed: RKE2 and Longhorn data.

In the future we think about distributing updates to our customers by sending them ISO files with new SLE Micro and RKE2/Longhorn versions. 

But if customers are updating their installations: How can we keep configuration (e.g. ETCD Data) and Longhorn storage data without having them overwritten? 

Should we create a seperate data partition for that scenario? If yes: How would we do that with EIB?

Thanks a lot and greetings,

Josef

**Comment by hardys** [comment]
Hi @jomeier - thanks for the question, it's certainly an interesting topic and I'm not sure I have a complete answer but here are a few thoughts:

In general EIB is designed as a day-1 tool, it builds on the SLEMicro self-install ISO capabilities and enables other workflows which consume raw images - currently there's no concept of retaining data on the target disk, and although perhaps it might be possible for 5.5 e.g via [autoyast config](https://documentation.suse.com/sle-micro/5.5/html/SLE-Micro-all/cha-configuration-installation-options.html#CreateProfile-Partitioning) in the self-install flow, that would not work for raw images, and it also won't work for 6.0+ AFAICS which [doesn't support autoyast anymore](https://www.suse.com/releasenotes/x86_64/SL-Micro/6.0/index.html).

For storage data specifically, I think generally it would be advisable to keep storage and OS data on different disks - in that scenario retaining data becomes easier and could potentially be combined with an OS-replacement rolling upgrade (this is actually how upgrades orchestrated via Cluster API work), but other than preparing the new image perhaps I think this upgrade automation is outside the scope of EIB currently.

That said the use-case of enabling in-place upgrades for standalone clusters has been discussed recently, and there is some [early work ongoing](https://github.com/suse-edge/upgrade-controller) - if you would like to share more details of your use-case it would certainly be interesting to understand if in future that work may be relevant.

**Comment by jomeier** [comment]
Hi @hardys - thanks for your response.

Let say if you use rke2 in products and want to upgrade the os and also rke2 without touching the k8s config and (persistent volume) data stored on the disk, it would be great if one simply could apply a new ISO image to that system and it would be possible to apply all patches, new os, ... automatically to the current installation.

Especially in a product scenario, where a customer is not experienced with Linux shells it might be great, to simply add the new ISO with everything included thats necessary for an upgrade. Even Docker images and rpm packages for air gapped scenarios.

Does that make sense?

Greetings,
Josef

**Comment by hardys** [comment]
Thanks @jomeier - yes it does make sense, I'm not sure if EIB is necessarily the right tool for that use-case, but some kind of workflow to create an image which can then be used for automated in-place upgrades is definitely valid, probably some additional discussion around the expected workflow and user experience would be a helpful next step.

**Comment by PidgeyBE** [comment]
I'm tinkering about the same workflow.
We would also need to update airgapped installations.
We can put all application data on a separate disk or partition (and use hostPath mounts in k8s), but the configuration of k3s/rke2 itself won't be stored on the separate disk I guess :thinking: 

Is it possible to also put `/var/lib/rancher/k3s/server` on a separate disk/partition?
https://docs.k3s.io/datastore/backup-restore

**Comment by jdob** [comment]
@PidgeyBE EIB currently does not have support for indicating the disk to install to. If this is still a desired requirement, please file a separate RFE (I'll be closing this out to finish off the conversation about the upgrade strategy).
