### ISSUE TITLE
Install nmc via zypper

### ISSUE THREAD

**Issue by atanasdinov** [suse-edge/edge-image-builder#51]
https://github.com/suse-edge/edge-image-builder/pull/48 introduces the network combustion component, however, we currently have to grab the nmc binary from a Github release since an RPM package does not yet exist.

This is inconvenient and poses limitations where cross building will fail due to incompatibility between x86_64 and aarch64 architectures.

**Comment by jdob** [comment]
This work will be tracked as part of #21
