### ISSUE TITLE
Leap Micro 6.0: Elemental Auto-Registration Broken - libopenssl1_1 Missing

### ISSUE THREAD

**Issue by swaphb** [suse-edge/edge-image-builder#522]
Attempting to auto-register a device flashed with an EIB-created ISO (Leap Micro 6.0 self-install) results in an error. The elemental-register command cannot execute because it requires libopenssl1_1, a library that has been dropped from recent Leap Micro versions. This renders the auto-registration process inoperable.

**Comment by rdoxenham** [comment]
Thanks for the report, @swaphb! Can you please elaborate on the version of Edge Image Builder that you're using here? I take it that you're deploying Elemental 1.4 versions if you're deploying with standard EIB?

**Comment by rdoxenham** [comment]
OK, I've reproduced it... 

```
Aug 07 20:25:01 localhost.localdomain elemental-register[4012]: /usr/sbin/elemental-register: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
```

This is a problem with openSUSE Leap Micro 6.0 (or SL Micro 6.0) when using Edge Image Builder 1.0, which is built for SUSE Edge 3.0, which uses Micro 5.5, and defaults to using Elemental 1.4 packages. In the next version of Edge Image Builder we will move to Elemental 1.6 packages which do not need this package to be installed on the host OS.

**Comment by swaphb** [comment]
Hi @rdoxenham , you are correct, I'm using EIB realsed with tag 1.0.1 and tried 1.0.2 as well. Glad you were able to replicate and that there is a path forward. Thanks for looking into this issue.

**Comment by dbw7** [comment]
With #549 and #569, you now must manually side-load the elemental RPMs when using elemental with Leap 6.0.
This entails something like going to https://download.opensuse.org/repositories/isv:/Rancher:/Elemental:/Staging/standard, downloading the elemental-system-agent and elemental-register RPMs manually, and then putting them into the rpms directory as specified in the [side-loading guide](https://github.com/suse-edge/edge-image-builder/blob/main/docs/building-images.md#rpms).
