### ISSUE TITLE
Add validation to the elemental registration for the dependent RPMs

### ISSUE THREAD

**Issue by jdob** [suse-edge/edge-image-builder#54]
In PR #53, it was landed without any validation that the necessary elemental RPMs are present. That's actually a tricky question to answer. This issue is to track the that we revisit this in the future when we have more information.

Possible options:

= Option 1: Force the user to name the files according to our convention, so something like `elemental-toolkit.rpm`

Pros:
- Makes validation simple
- Continues to use the existing RPM install functionality at no extra cost to us

Cons:
- Adds another manual step for the user to do
- Removes version/arch/whatever else information from the RPM name
- Relies on documentation to convey the convention, as compared to Option 3 which is more explicit

= Option 2: Have the validation logic only check for the prefix of the RPM, making sure there are RPMs that start with `elemental-toolkit` and `elemental-system-agent`

Pros:
- Continues to use the existing RPM install functionality at no extra cost to us
- User shouldn't need to do any extra renaming steps in most cases

Cons:
- Validation is a bit on the fragile side
- Relies on documentation to convey the convention, as compared to Option 3 which is more explicit

= Option 3: Have the user specify the names of these files in the image definition, and still adding

Pros:
- Can still use the existing RPM functionality; the image just won't be built if EIB can't find them by name

Cons:
- Extra data needs to be added to the image definition. _(jdob: I don't hate that; the magic of just dropping it in `rpms` is nice but there is something to be said about having the elemental pieces not work on magic)_

= Option 4: Have the user create an `elemental` directory in the image config dir and include the RPMs in there

Pros:
- Arguably clean, since it makes it obvious what those RPMs are in there for as compared to the catch-all `rpms` directory
- Doesn't use the existing RPM functionality at all, instead injecting the names of the RPMs into the template for elemental registration, thus removing the cross-component dependency

Cons:
- Still need to figure out how to resolve the potential name differences (see Options 1 and 2)
- Potentially confusing why there would be RPMs outside of the `rpms` directory _(jdob: I don't think this is a huge issue)_

= Option 5: Pre-download the RPMs into the EIB container (similar to what NMC does) and use those

Pros:
- Validating the RPMs becomes a non-issue, since we know they exist

Cons:
- Locks the user into specific versions of the elemental RPMs. Adding a way to override it brings us back to the previous options for consideration.

**Comment by atanasdinov** [comment]
Thanks for the comprehensive and thoughtful considerations! I really prefer option 5 but it also implies that we know exactly where to grab the RPMs from which has to be further investigated.

We also need to know how to get both x86_64 and aarch64 packages in the deliverable image which was trivial for nmc but unknown if we have `zypper in --download-only` in mind. I imagine getting these directly from SUSE repository URLs might involve authentication of some sort.

**Comment by rdoxenham** [comment]
I'm also +1 on option 5 as it enables us to version lock and not introduce untested code paths accidentally.

**Comment by atanasdinov** [comment]
We should be able to leverage the downloader introduced in https://github.com/suse-edge/edge-image-builder/pull/82 if going for Option 5.

**Comment by jdob** [comment]
The approach chosen here should be the same as we use for the SELinux RPM needs.

**Comment by atanasdinov** [comment]
Implemented in https://github.com/suse-edge/edge-image-builder/pull/175.
