### ISSUE TITLE
Rebooting the node provisioned using EIB built ISO fails randomly

### ISSUE THREAD

**Issue by fdegir** [suse-edge/edge-image-builder#556]
A node that's provisioned with an image built using `EIB 1.1 RC2` and `SL Micro 6.0` fails to reboot randomly when the reboot is initiated in an automated manner using Ansible.

The lines from `journalctl` below contains error messages regarding the call `syslogin_perform_logout` and this may be the thing causing system to inhibit the reboot.

```
Sep 06 08:49:40 node1.suse.com sshd[1636]: syslogin_perform_logout: logout() returned an error
Sep 06 08:49:40 node1.suse.com sshd[1636]: syslogin_perform_logout: logout() returned an error
```

Please note that the issue with not being able to disable `rebootmgr` described in the issue #555 is probably the source of this random behaviour since explicitly disabling `rebootmgr` in a separate Ansible task once the system completes the initial boot and rebooting the node works as expected.

**Comment by jdob** [comment]
@fdegir We discussed this in our triage. From the sound of it, it doesn't seem like an EIB issue, but rather the interaction between ansible and the started node. I'm going to close this out, but if that's not the case please let me know and we'll revisit.
