### ISSUE TITLE
[RFE] Add dates to the release notes

### ISSUE THREAD

**Issue by e-minguez** [suse-edge/edge-image-builder#563]
It would be nice to have the dates when the different EIB versions were released in the release notes. Currently they can be seen in the https://github.com/suse-edge/edge-image-builder/tags (not in the releases).

**Comment by jiwonhu** [comment]
I found that our documentations are hosted in two places. One is SUSE Edge and another is EIB repo. I guess you are referring to [this SUSE Edge release note](https://documentation.suse.com/suse-edge/3.0/html/edge/id-release-notes.html)? This doesn't have EIB specific releases.

If we continue to use EIB repo for EIB specific docs, it'd be nice to create releases and release notes in EIB repo, like [this](https://github.com/rancher/rancher/releases/tag/v2.9.1).
