### ISSUE TITLE
README update: 1.1.0 release refers to EIB 1.0.2 image

### ISSUE THREAD

**Issue by pbronneberg** [suse-edge/edge-image-builder#570]
I wanted to execute a spike on using EIB 1.1.0 now that it's released, but noticed that the README still refers to 1.0.2.

I suggest to update the instructions in README.md to the following
```
podman pull registry.opensuse.org/isv/suse/edge/edgeimagebuilder/containerfile-sp6/suse/edge-image-builder:1.1.0
```

Also perhaps indicate in the README that 1.1.0 is not intended for SLE Micro 5.5

**Comment by atanasdinov** [comment]
Thanks, both! We're well aware and will soon update our docs. :)
