### ISSUE TITLE
Missing docs of how we shall use the .../custom/files folder

### ISSUE THREAD

**Issue by jomeier** [suse-edge/edge-image-builder#571]
Hi,
could you please provide an example of how to use custom files in the custom/files folder in the docs?
I want to copy some files to the file system in my home directory during combustion phase.

custom/files:
myfile
myscript.sh

Content of myscript.sh:
```
cp myfile /home/myname
```

For that I placed the file and a script in custom/files folder. I expected that the script will be called and the file will be copied to my home folder but this does not work. 
What is wrong with this procedure?

Thanks and greetings,
Josef

**Comment by Miaoxiang-philips** [comment]
Hi @jomeier , Can you try it like this?

```shell
mount /home
cp myfile /home/myname
umount /home
```

**Comment by jomeier** [comment]
> Hi @jomeier , Can you try it like this?
> 
> ```shell
> mount /home
> cp myfile /home/myname
> umount /home
> ```

Will scripts in custom/files automatically be started during the combustion phase?

**Comment by jomeier** [comment]
That works! Thank you for the hint. Ticket can be closed.
