### ISSUE TITLE
Scripts injection ordering

### ISSUE THREAD

**Issue by e-minguez** [suse-edge/edge-image-builder#62]
AFAIK the idea is to have scripts injected based on the prefix number (aka 00-foo.sh, 01-bar.sh, etc.), which is ok but this gives a few more scenarios:

* Do we want to reserve some of them for EIB internal stuff? How?

I think the idea was to reserve some numbers for EIB and let others for custom stuff. For me I think this convention over configuration is confusing... for example >50 for custom stuff. Why >50? a customer may ask.

I'd say we can instead do something like:
* The script file will run first the scripts present in the scripts/eib (ordered by XY_foobar.sh)
* Then the ones in the scripts/custom (names may vary), which will be the ones that the user can drop.

Something like:

* The script file will run first the scripts present in the scripts/eib (ordered by XY_foobar.sh)
* Then the ones in the scripts/custom(names may vary), which will be the ones that the user can drop.

However, there may be cases where we need to support "pre" EIB tasks (for example loading some special driver to enable networking or similar).

**Comment by jdob** [comment]
We discussed this and came to the agreement that the limitations of explicitly forcing our scripts to run before customers aren't worth the trade off of the user needing to know the two different ranges. Especially as new as this project is, I don't want us to encounter a situation where a user needs to inject something earlier in the combustion process and not be able to.

I created #83 to both revisit our existing scripts (once we're closer to 1.0 MVP) to make sure we're happy with our usage of the prefixes and also make sure we clearly document how users should name their scripts.
