### ISSUE TITLE
EIB fails when custom directories are empty

### ISSUE THREAD

**Issue by rdoxenham** [suse-edge/edge-image-builder#73]
We should likely skip over the custom directory if it's empty rather than failing...

```
rdo@woden:~/work/eib-suma% cat _build/eib-build-Jan02_12-58-47.log
2024-01-02T12:58:47.012Z	FATAL	eib/main.go:120	An error occurred building the image	{"error": "configuring combustion: configuring component \"custom files\": no files found in directory /eib/custom/files"}
main.main
	/src/cmd/eib/main.go:120
runtime.main
	/usr/lib64/go/1.21/src/runtime/proc.go:267
```

**Comment by atanasdinov** [comment]
If there's a `custom` directory, then EIB will consider the `custom` component to be configured (i.e. it will not finish with a `SKIPPED` status).

In my opinion, having a `SUCCESS` status on empty directories is much more misleading to the user than an `ERROR` in those cases.

**Comment by rdoxenham** [comment]
Good call.
