### ISSUE TITLE
suma host validation

### ISSUE THREAD

**Issue by dbw7** [suse-edge/edge-image-builder#80]
During image definition validation, we want to validate Suma hostnames so the user knows if their hostname is invalid before creating the image. The current implementation only checks for a non empty string that does not start with “https://” or “http://”  
 
In the future, we want to have a more comprehensive hostname validation check but there are too many differing edge cases to investigate at the moment.

**Comment by jdob** [comment]
We will potentially reopen if this becomes a recurring problem by users.
