### ISSUE TITLE
Podman testing scenarios

### ISSUE THREAD

**Issue by ipetrov117** [suse-edge/edge-image-builder#88]
We need to come up with a testing scenario for the functionality introduced by #86. Relates to this [comment](https://github.com/suse-edge/edge-image-builder/pull/86#discussion_r1446109919).

Basically an integration test would be favourable over a unit test. Mainly because in order to test the podman logic we need a [podman-system-service](https://docs.podman.io/en/latest/markdown/podman-system-service.1.html) started, which will be very hard to mock as part of a unit test.

**Comment by jdob** [comment]
This is on our radar for CI testing. Closing out this issue as it will be addressed there.
